### ISSUE TITLE
Not Working Docs

### ISSUE THREAD

**Issue by Hansel03** [scoursen/django-softdelete#16]
I did everything but the documentation indicates not work, note that the name of the application that is placed in the Settings is bad.

SafeDelete instead of softdelete

INSTALLED_APPS = (
...
     'django.contrib.contenttypes'
     'softdelete'
)

I'm working:

INSTALLED_APPS = (
...
     'django.contrib.contenttypes'
     'safedelete'
)

models also have to import it:

from safedelete import safedelete_mixin_factory,HARD_DELETE_NOCASCADE

**Comment by scoursen** [comment]
This is not the project that you are trying to use.  You are trying to use
a project called "django-safedelete".  This project is "django-softdelete".
