### ISSUE TITLE
Push new version to PyPI

### ISSUE THREAD

**Issue by decibyte** [scoursen/django-softdelete#18]
The last release on PyPI is from 2012-03-30. Both Django 1.8 and 1.9 is incompatible with that old version. Can you push an update to PyPI?

Thanks in advance!

**Comment by decibyte** [comment]
*bump*

**Comment by scoursen** [comment]
sorry for delay, got lost in a shuffle of email config changes.  should be updated now, version 0.4.0

**Comment by decibyte** [comment]
Thanks a lot, man! :)
