### ISSUE TITLE
Make python 3 compatible

### ISSUE THREAD

**Issue by morenoh149** [scoursen/django-softdelete#25]
I can't run this module in python 3. The first error I run into is `'QueryDict' object has no attribute 'has_key'` at https://github.com/scoursen/django-softdelete/blob/228108e7e5b9793acf69e62405f10224f2aa5277/softdelete/admin/forms.py#L21

This could be replaced with `if 'undelete' in self.data`

cc @alexahn @vivekbhagwat

**Comment by alexahn** [comment]
See https://github.com/scoursen/django-softdelete/pull/26
