### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by morenoh149** [scoursen/django-softdelete#27]
can we get version bump to 0.4.3 and release onto PyPI please

**Comment by glynjackson** [comment]
Any chance of a PyPi release with to 0.7.1 with the Python 3 changes already merged :) 👍   Thanks

**Comment by morenoh149** [comment]
@scoursen seems to have update the pypi release to current stable. thanks https://pypi.python.org/pypi/django-softdelete/0.7.0

**Comment by blag** [comment]
Excellent! Thanks @scoursen!
