### ISSUE TITLE
Failing to see if row already exists?

### ISSUE THREAD

**Issue by Tatsh** [scoursen/django-softdelete#30]
This is a little hard to fully explain as I do not know the exact cause of the issue. I am getting an INSERT where an UPDATE should be occurring.

The model is like this:

``` python
class Address(SoftDeleteObject):
    field_name = models.CharField(max_length=30)

class UserDetails(SoftDeleteObject):
    address = models.OneToOneField(Address, on_delete=models.CASCADE, blank=True, null=True)
```

The data processing is through model formsets, like so:

``` python
if form.is_valid():
    user = form.save(commit=False)

    if details_formset.is_valid() and address_formset.is_valid():
        user.save()
        form.save_m2m()
        details_formset.save()
        address_formset.save()
```

About 6 times in a week, this error has popped up:

```
IntegrityError: duplicate key value violates unique constraint "game_address_user_id_key"
DETAIL:  Key (user_id)=(3924) already exists.
```

Stack trace:

```
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)

  File "game/views/account.py", line 76, in post
    address_formset.save()

  File "django/forms/models.py", line 640, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "django/forms/models.py", line 771, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "django/forms/models.py", line 904, in save_new
    obj.save()
  File "game/models.py", line 196, in save
    super(Address, self).save(*args, **kwargs)
  File "softdelete/models.py", line 244, in save
    super(SoftDeleteObject, self).save(**kwargs)
  File "django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
```

**Comment by AndySun25** [comment]
This is an issue I've been seeing after attempting to update to Django 1.10 (previously on 1.9) and it is also present on makinacorpus/django-safedelete.

Still investigating the exact cause of the error but it seems to happen directly after this line as `self._save_table(...)` is returning false. https://github.com/django/django/blob/master/django/db/models/base.py#L830

**Comment by Tatsh** [comment]
Glad I'm not the only one but I am getting this with latest version on 1.8.

**Comment by Tatsh** [comment]
The cause might be extra unnecessary unrelated fields that are confusing to SoftDelete. For example what I had:

```python
class Address(SoftDeleteObject):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    field_name = models.CharField(max_length=30)

class UserDetails(SoftDeleteObject):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    address = models.OneToOneField(Address, on_delete=models.CASCADE, blank=True, null=True)
```

Note how both have `user` in the same way but `UserDetails` also has address. Nowhere in my code did    I ever access `user.userdetails.address` and rather I use `user.address` (shorter is better arguably). So I removed the `address` field.

Also note that I have not proven this is the problem because I have not reproduced the exception. This was just an anomaly in my data model that I fixed. It seems plausible SoftDelete gets confused because Django (or something) inadvertently inserts a row for `Address` (maybe because of `User` association) before `UserDetails.save` ever gets called.

**Comment by Tatsh** [comment]
Theory was wrong. Got the error again. Still unsure.

**Comment by AndySun25** [comment]
I think I found the issue, note that I haven't had time yet to test with this library (only tested with safedelete, but the theory is identical judging by the code base).

In my case the actual issue was masked by my use of django-polymorphic, django will first update parent tables when updating objects spread across relations. After abandoning third party logical delete solutions I implemented my own in-house safe delete mixin/model and found the issue.

https://github.com/django/django/blob/master/django/db/models/base.py#L891
Here you can see that an during update the manager is instantiated to locate the update object, however something has changed that causes soft-deleted objects to be discarded from this queryset; when django is unable to find the soft deleted object it attempts to insert a new record at which point an integrity error will be thrown at the database level.

Try overriding the `get_queryset()` method here and disregard `deleted_at` and test soft deleting again. While this certainly isn't the solution it should help identify the root of the issue.
https://github.com/scoursen/django-softdelete/blob/master/softdelete/models.py#L104
