### ISSUE TITLE
Respect the `on_delete` argument to ForeignKey fields

### ISSUE THREAD

**Issue by decibyte** [scoursen/django-softdelete#45]
Django docs: https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey.on_delete

`django-softdelete` README:

> When you soft-delete an object, any objects referencing it via a ForeignKey, ManyToManyField, or OneToOneField will also be soft-deleted. This mimics the traditional CASCADE behavior of a SQL DELETE.

I've spend a whole day trying to figure out why `on_delete=models.SET_NULL` (or any value other than `CASCADE`) didn't work as expected for some models using `django-softdelete`.

Would it be possible to make `django-softdelete` act in different (expected) ways, depeneding on the value of `on_delete`? I'd be happy to provide a pull request if you can guide me in the right direction.

**Comment by daadu** [comment]
This is a great project and an app. I am not able to use it because of the lack of this feature.

I am thinking to develop this. Let me know if you (or anyone) have any pointers.

**Comment by daadu** [comment]
Looks like this is not trivial, and lack of documentation, this takes more effort than I predicted.

**Comment by PratikBodawala** [comment]
@daadu @decibyte I have opened pull request for this fix, in pr #86. Do let me know if this fix works for you.
