### ISSUE TITLE
Latest Release 0.9.1 (Req'd For Django==3.0) Not on PyPI

### ISSUE THREAD

**Issue by jjorissen52** [scoursen/django-softdelete#65]
You encounter this following error when using Django 3:

```
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/Users/me/.pyenv/versions/trades-portal/lib/python3.7/site-packages/django/utils/encoding.py)
```

Upgrading to patch 0.9.1 would fix the issue because of [This commit](https://github.com/scoursen/django-softdelete/commit/f784e56e46d170021d4acb1e87d9c5c1ac626edb) (currently in master), but it is not available in PyPI.

**Comment by scoursen** [comment]
Just built & uploaded via twine.

**Comment by jjorissen52** [comment]
Thanks!
