### ISSUE TITLE
New PyPi release needed to stop generating migrations files for package

### ISSUE THREAD

**Issue by antsankov** [scoursen/django-softdelete#89]
In the latest release of django-softdelete, [0.9.3](https://pypi.org/project/django-softdelete/0.9.3/) -- Django `makemigrations` is generating a migration file for the softdelete package itself.

Based on this PR https://github.com/scoursen/django-softdelete/pull/88 (merged a week ago) it changes the default ID generation, so that a migration file is no longer generated

A release of the current `master` branch to PyPi should solve this issue.

Example:
```
$ ./manage.py makemigrations
Migrations for 'softdelete':
  /usr/local/lib/python3.8/dist-packages/softdelete/migrations/0004_alter_changeset_id_alter_softdeleterecord_id.py
    - Alter field id on changeset
    - Alter field id on softdeleterecord
```

**Comment by PeterCarnesciali-minted** [comment]
Yes, please make a new release so we can use that fix.

**Comment by stevecoursen** [comment]
I think I uploaded to pypi correctly.

**Comment by scoursen** [comment]
I think it's been uploaded to pypi correctly.
